[package]
name = "winit-softbuffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.5"
softbuffer = "0.4.6"
winit = "0.30.8"
